name: epubview
description: Widgets for epub, chapter list and reader's view
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  epub3:
  html2md: ^1.3.1
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+6
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

dependency_overrides:
  epub3:
      path: ../epub3
