include: package:lints/recommended.yaml

linter:
  rules:
    avoid_shadowing_type_parameters: false
    await_only_futures: true
    use_string_in_part_of_directives: false # https://dart.dev/tools/linter-rules/use_string_in_part_of_directives
    hash_and_equals: false
    todo: ignore
