name: epubrs
description: EPUB Reading Systems
homepage: https://github.com/pedia/epubrs
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.1.6
  collection: ^1.15.0
  fpdart: ^1.1.0
  image: ^4.1.7
  path: ^1.8.1
  quiver: ^3.0.1+1
  xml: ^6.0.1


dev_dependencies:
  test: ^1.16.7
  pedantic: ^1.11.0
