name: epubrs
description: EPUB Reading Systems
homepage: https://github.com/pedia/epubrs
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  fpdart: ^1.1.0
  image: ^4.1.7
  path: ^1.9.0
  quiver: ^3.2.1
  xml: ^6.5.0


dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
