name: epub3
description: Read and Write Epub3 files.
homepage: https://github.com/pedia/epub3
version: 0.3.0

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  archive: ^3.2.2
  collection: ^1.16.0
  fpdart: ^0.0.14
  image: ^3.1.3
  path: ^1.8.1
  quiver: ^3.0.1
  xml: ^6.3.0
  uuid: ^3.0.6

dev_dependencies:
  test: ^1.18.1
  lints: ^1.0.1
  http: ^0.13.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - epub
  - book
