name: web_ex
description: An absolute bare-bones web app.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  epub3:
    path: ../..
  archive: ^3.4.10
  web: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
